export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const ProfileConstants = {
  PROFILE_REQUEST: "PROFILE_REQUEST",
  PROFILE_AVATAR_REQUEST: "PROFILE_AVATAR_REQUEST",
  PROFILE_AVATAR_SUCCESS: "PROFILE_AVATAR_SUCCESS",
  PROFILE_SUCCESS: "PROFILE_SUCCESS",
  ORGANIZATION_PROFILE_SUCCESS: "ORGANIZATION_PROFILE_SUCCESS",
  ORGANIZATION_PROFILE_REQUEST: "ORGANIZATION_PROFILE_REQUEST",
  ORGANIZATION_PROFILE_FAILURE: "ORGANIZATION_PROFILE_FAILURE",
};
export const ProjectConstants = {
  PROJECT_CREATE_REQUEST: "PROJECT_CREATE_REQUEST",
  PROJECT_CREATE_SUCCESS: "PROJECT_CREATE_SUCCESS",
  PROJECT_CREATE_FAILURE: "PROJECT_CREATE_FAILURE",
  PROJECT_GET: "PROJECT_GET",
  ALL_PROJECTS_GET: "ALL_PROJECTS_GET",
};

export const diagramConstant = {
  ADDEDGE: "ADDEDGE",
  ADD_VALUE_STREAM: "ADD_VALUE_STREAM",
  DELETE_VALUE_STREAM: "DELETE_VALUE_STREAM",
  UPDATE_VALUE_STREAM: "UPDATE_VALUE_STREAM",
  GET_VALUE_STREAM: "GET_VALUE_STREAM",
  ADD_NEW_PERSONA: "ADD_NEW_PERSONA",
  GET_PERSONA_DATA: "GET_PERSONA_DATA",
  UPDATE_PERSONA_DATA: "UPDATE_PERSONA_DATA",
  LOADDATA: "LOADDATA",
  LOAD_TABLE_DATA_FROM_BACKEND: 'LOAD_TABLE_DATA_FROM_BACKEND',
  ADD_NEW_FORM_NODE_DATA: 'ADD_NEW_FORM_NODE_DATA',
  CLOSE_FORM_NODE_DATA: 'CLOSE_FORM_NODE_DATA',
  UPDATE_NEW_FORM_NODE_DATA: 'UPDATE_NEW_FORM_NODE_DATA',
  DELETE_NEW_FORM_NODE_DATA: 'DELETE_NEW_FORM_NODE_DATA',
  FOR_CSV_WITH_VALUE_STREAM: 'FOR_CSV_WITH_VALUE_STREAM',
};

export const websocketConstant = {
  ONCONNECT: 'ONCONNECT',
  DISCONNECT: 'DISCONNECT',
  REF_CONNECT: 'REF_CONNECT',
  SENDMESSAGE: 'SENDMESSAGE',
}
